sudo: required

services:
  - docker

env:
  global:
    IMAGE: tethysts/tethys-db-initialize:$TRAVIS_BRANCH

# before_script:
#   - docker pull $IMAGE || true
#
# script:
#   - docker build --cache-from $IMAGE --tag $IMAGE .

script:
  - docker build --tag $IMAGE .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $IMAGE
