version: '3'

services:
  db-int:
    image: mongo:4.2-bionic
    command: --wiredTigerJournalCompressor zstd --wiredTigerCollectionBlockCompressor zstd
    ports:
      - "27017:27017"
  db-initialize:
    image: tethysts/tethys-db-initialize:1.2
    environment:
      db_service: db-int
    volumes:
        - "/media/sdb1/Projects/git/tethys/tethys-db-initialize/parameters.yml:/parameters.yml"
    depends_on:
      - "db"
  # updater:
  #   image: tethys-updater
  #   environment:
  #     DATABASE: tethys
  #     RW_USERNAME: readwriter
  #     RW_PASSWORD: readwriter
  #   depends_on:
  #     - "db-initialize"
